In [1]:
import numpy as np
import sympy as smp
smp.init_session()

IPython console for SymPy 1.2 (Python 3.6.6-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at http://docs.sympy.org/1.2/



In [3]:
a1 = np.array((3, -1,-1,1))
a2 = np.array((-5,5,3,-1))
a3 = np.array((7,7,5,3))
a4 = np.array((1,1,-1,-3))

In [4]:
e1 = a1
e2 = a2 - (e1.dot(a2)/e1.dot(e1))*e1
e3 = a3 - (e2.dot(a3)/e2.dot(e2))*e2 - (e1.dot(a3)/e1.dot(e1))*e1
e4 = a4 - (e3.dot(a4)/e3.dot(e3))*e3 - (e2.dot(a4)/e2.dot(e2))*e2 - (e1.dot(a4)/e1.dot(e1))*e1
e1, e2, e3, e4

(array([ 3, -1, -1,  1]),
 array([1., 3., 1., 1.]),
 array([ 1., -1.,  3., -1.]),
 array([ 1.,  1., -1., -3.]))

In [45]:
C = np.matrix((e1, e2, e3, e4)).T
print(C)
print(np.linalg.det(C))
print(C.I)
print('='*96)
rows = C.shape[0]
cols = C.shape[1]
IC = np.matrix((e1, e2, e3, e4)).T
for x in range(rows):
    for y in range(cols):
        elem = smp.S(int(C[x,y]))
        print(type(elem))
        IC[x,y] = elem
Cm = smp.Matrix(IC)
Cm_new = smp.Matrix(IC)
print(IC)
print(type(Cm[0,0]))
for x in range(rows):
    for y in range(cols):
        elem = smp.S(int(Cm[x,y]))
        print(type(elem))
        Cm[x,y] = elem
for x in range(rows):
    for y in range(cols):
        elem = smp.S(int(Cm_new[x,y]))
        Cm_new[x,y] = elem
Cm, Cm_new

[[ 3.  1.  1.  1.]
 [-1.  3. -1.  1.]
 [-1.  1.  3. -1.]
 [ 1.  1. -1. -3.]]
-144.0
[[ 0.25       -0.08333333 -0.08333333  0.08333333]
 [ 0.08333333  0.25        0.08333333  0.08333333]
 [ 0.08333333 -0.08333333  0.25       -0.08333333]
 [ 0.08333333  0.08333333 -0.08333333 -0.25      ]]
<class 'sympy.core.numbers.Integer'>
<class 'sympy.core.numbers.One'>
<class 'sympy.core.numbers.One'>
<class 'sympy.core.numbers.One'>
<class 'sympy.core.numbers.NegativeOne'>
<class 'sympy.core.numbers.Integer'>
<class 'sympy.core.numbers.NegativeOne'>
<class 'sympy.core.numbers.One'>
<class 'sympy.core.numbers.NegativeOne'>
<class 'sympy.core.numbers.One'>
<class 'sympy.core.numbers.Integer'>
<class 'sympy.core.numbers.NegativeOne'>
<class 'sympy.core.numbers.One'>
<class 'sympy.core.numbers.One'>
<class 'sympy.core.numbers.NegativeOne'>
<class 'sympy.core.numbers.Integer'>
[[ 3.  1.  1.  1.]
 [-1.  3. -1.  1.]
 [-1.  1.  3. -1.]
 [ 1.  1. -1. -3.]]
<class 'sympy.core.numbers.Float'>
<class 'sympy.c

⎛⎡3   1  1   1 ⎤  ⎡3   1  1   1 ⎤⎞
⎜⎢             ⎥  ⎢             ⎥⎟
⎜⎢-1  3  -1  1 ⎥  ⎢-1  3  -1  1 ⎥⎟
⎜⎢             ⎥, ⎢             ⎥⎟
⎜⎢-1  1  3   -1⎥  ⎢-1  1  3   -1⎥⎟
⎜⎢             ⎥  ⎢             ⎥⎟
⎝⎣1   1  -1  -3⎦  ⎣1   1  -1  -3⎦⎠

In [6]:
Cm**-1

⎡1/4   -1/12  -1/12  1/12 ⎤
⎢                         ⎥
⎢1/12   1/4   1/12   1/12 ⎥
⎢                         ⎥
⎢1/12  -1/12   1/4   -1/12⎥
⎢                         ⎥
⎣1/12  1/12   -1/12  -1/4 ⎦

In [55]:
Cm2 = Cm**-1
Cm2[0,:]*(smp.S(1)/4)

[1/16  -1/48  -1/48  1/48]

In [42]:
E = smp.eye(4)
E

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦

In [45]:
Cm*Cm2

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦

In [9]:
Cm, Cm2, Cm.shape

⎛⎡3   1  1   1 ⎤  ⎡1/4   -1/12  -1/12  1/12 ⎤        ⎞
⎜⎢             ⎥  ⎢                         ⎥        ⎟
⎜⎢-1  3  -1  1 ⎥  ⎢1/12   1/4   1/12   1/12 ⎥        ⎟
⎜⎢             ⎥, ⎢                         ⎥, (4, 4)⎟
⎜⎢-1  1  3   -1⎥  ⎢1/12  -1/12   1/4   -1/12⎥        ⎟
⎜⎢             ⎥  ⎢                         ⎥        ⎟
⎝⎣1   1  -1  -3⎦  ⎣1/12  1/12   -1/12  -1/4 ⎦        ⎠

In [32]:
class InvMatrixFinder():
    def __init__(self, M):
        #self.base_M = M
        #self.base_E = E
        self.M = M
        self.E = smp.eye(M.shape[0])
    
    def compute(self, expr, adr1, adr2, mode):
        adr1 -= 1
        adr2 -= 1
        if adr1 == adr2:
            if mode == 'r':
                self.M[adr1,:] = self.M.row(adr1)*expr
                self.E[adr1,:] = self.E.row(adr1)*expr
            elif mode == 'c':
                self.M[:,adr1] = self.M.col(adr1)*expr
                self.E[:,adr1] = self.E.col(adr1)*expr
        else:
            if mode == 'r':
                #for M
                new_row = self.M.row(adr2)*expr
                self.M[adr1,:] = self.M[adr1,:] + new_row
                #for E
                new_row = self.E.row(adr2)*expr
                self.E[adr1,:] = self.E[adr1,:] + new_row
            elif mode == 'c':
                #for M
                new_col = self.M.col(adr2)*expr
                self.M[:,adr1] = self.M[:,adr1] + new_col
                #for E
                new_col = self.E.col(adr2)*expr
                self.E[:,adr1] = self.E[:,adr1] + new_col

In [26]:
Cm_new, smp.eye(4)

⎛⎡3   1  1   1 ⎤  ⎡1  0  0  0⎤⎞
⎜⎢             ⎥  ⎢          ⎥⎟
⎜⎢-1  3  -1  1 ⎥  ⎢0  1  0  0⎥⎟
⎜⎢             ⎥, ⎢          ⎥⎟
⎜⎢-1  1  3   -1⎥  ⎢0  0  1  0⎥⎟
⎜⎢             ⎥  ⎢          ⎥⎟
⎝⎣1   1  -1  -3⎦  ⎣0  0  0  1⎦⎠

# Начало расчета 1

In [46]:
imf = InvMatrixFinder(Cm_new)
imf.compute(smp.S(1)/3, adr1=1, adr2=1, mode='r')
imf.M, imf.E

⎛⎡1   1/3  1/3  1/3⎤  ⎡1/3  0  0  0⎤⎞
⎜⎢                 ⎥  ⎢            ⎥⎟
⎜⎢-1   3   -1    1 ⎥  ⎢ 0   1  0  0⎥⎟
⎜⎢                 ⎥, ⎢            ⎥⎟
⎜⎢-1   1    3   -1 ⎥  ⎢ 0   0  1  0⎥⎟
⎜⎢                 ⎥  ⎢            ⎥⎟
⎝⎣1    1   -1   -3 ⎦  ⎣ 0   0  0  1⎦⎠

In [47]:
imf.compute(smp.S(1)/-3, adr1=2, adr2=1, mode='c')
imf.M, imf.E

⎛⎡1    0    1/3  1/3⎤  ⎡1/3  -1/9  0  0⎤⎞
⎜⎢                  ⎥  ⎢               ⎥⎟
⎜⎢-1  10/3  -1    1 ⎥  ⎢ 0    1    0  0⎥⎟
⎜⎢                  ⎥, ⎢               ⎥⎟
⎜⎢-1  4/3    3   -1 ⎥  ⎢ 0    0    1  0⎥⎟
⎜⎢                  ⎥  ⎢               ⎥⎟
⎝⎣1   2/3   -1   -3 ⎦  ⎣ 0    0    0  1⎦⎠

In [48]:
imf.compute(smp.S(1)/-3, adr1=3, adr2=1, mode='c')
imf.M, imf.E

⎛⎡1    0     0    1/3⎤  ⎡1/3  -1/9  -1/9  0⎤⎞
⎜⎢                   ⎥  ⎢                  ⎥⎟
⎜⎢-1  10/3  -2/3   1 ⎥  ⎢ 0    1     0    0⎥⎟
⎜⎢                   ⎥, ⎢                  ⎥⎟
⎜⎢-1  4/3   10/3  -1 ⎥  ⎢ 0    0     1    0⎥⎟
⎜⎢                   ⎥  ⎢                  ⎥⎟
⎝⎣1   2/3   -4/3  -3 ⎦  ⎣ 0    0     0    1⎦⎠

In [49]:
imf.compute(smp.S(1)/-3, adr1=4, adr2=1, mode='c')
imf.M, imf.E

⎛⎡1    0     0      0  ⎤  ⎡1/3  -1/9  -1/9  -1/9⎤⎞
⎜⎢                     ⎥  ⎢                     ⎥⎟
⎜⎢-1  10/3  -2/3   4/3 ⎥  ⎢ 0    1     0     0  ⎥⎟
⎜⎢                     ⎥, ⎢                     ⎥⎟
⎜⎢-1  4/3   10/3  -2/3 ⎥  ⎢ 0    0     1     0  ⎥⎟
⎜⎢                     ⎥  ⎢                     ⎥⎟
⎝⎣1   2/3   -4/3  -10/3⎦  ⎣ 0    0     0     1  ⎦⎠

In [50]:
imf.compute(smp.S(1)/1, adr1=2, adr2=1, mode='r')
imf.M, imf.E

⎛⎡1    0     0      0  ⎤  ⎡1/3  -1/9  -1/9  -1/9⎤⎞
⎜⎢                     ⎥  ⎢                     ⎥⎟
⎜⎢0   10/3  -2/3   4/3 ⎥  ⎢1/3  8/9   -1/9  -1/9⎥⎟
⎜⎢                     ⎥, ⎢                     ⎥⎟
⎜⎢-1  4/3   10/3  -2/3 ⎥  ⎢ 0    0     1     0  ⎥⎟
⎜⎢                     ⎥  ⎢                     ⎥⎟
⎝⎣1   2/3   -4/3  -10/3⎦  ⎣ 0    0     0     1  ⎦⎠

In [51]:
imf.compute(smp.S(3)/10, adr1=2, adr2=2, mode='r')
imf.M, imf.E

⎛⎡1    0    0      0  ⎤  ⎡1/3   -1/9  -1/9   -1/9 ⎤⎞
⎜⎢                    ⎥  ⎢                        ⎥⎟
⎜⎢0    1   -1/5   2/5 ⎥  ⎢1/10  4/15  -1/30  -1/30⎥⎟
⎜⎢                    ⎥, ⎢                        ⎥⎟
⎜⎢-1  4/3  10/3  -2/3 ⎥  ⎢ 0     0      1      0  ⎥⎟
⎜⎢                    ⎥  ⎢                        ⎥⎟
⎝⎣1   2/3  -4/3  -10/3⎦  ⎣ 0     0      0      1  ⎦⎠

In [52]:
imf.compute(smp.S(1)/5, adr1=3, adr2=2, mode='c')
imf.M, imf.E

⎛⎡1    0    0      0  ⎤  ⎡1/3   -1/9  -2/15  -1/9 ⎤⎞
⎜⎢                    ⎥  ⎢                        ⎥⎟
⎜⎢0    1    0     2/5 ⎥  ⎢1/10  4/15  1/50   -1/30⎥⎟
⎜⎢                    ⎥, ⎢                        ⎥⎟
⎜⎢-1  4/3  18/5  -2/3 ⎥  ⎢ 0     0      1      0  ⎥⎟
⎜⎢                    ⎥  ⎢                        ⎥⎟
⎝⎣1   2/3  -6/5  -10/3⎦  ⎣ 0     0      0      1  ⎦⎠

In [53]:
imf.compute(smp.S(2)/-5, adr1=4, adr2=2, mode='c')
imf.M, imf.E

⎛⎡1    0    0      0  ⎤  ⎡1/3   -1/9  -2/15  -1/15⎤⎞
⎜⎢                    ⎥  ⎢                        ⎥⎟
⎜⎢0    1    0      0  ⎥  ⎢1/10  4/15  1/50   -7/50⎥⎟
⎜⎢                    ⎥, ⎢                        ⎥⎟
⎜⎢-1  4/3  18/5  -6/5 ⎥  ⎢ 0     0      1      0  ⎥⎟
⎜⎢                    ⎥  ⎢                        ⎥⎟
⎝⎣1   2/3  -6/5  -18/5⎦  ⎣ 0     0      0      1  ⎦⎠

In [54]:
imf.compute(smp.S(1)/1, adr1=3, adr2=1, mode='r')
imf.M, imf.E

⎛                       ⎡1/3   -1/9  -2/15  -1/15⎤⎞
⎜⎡1   0    0      0  ⎤  ⎢                        ⎥⎟
⎜⎢                   ⎥  ⎢1/10  4/15  1/50   -7/50⎥⎟
⎜⎢0   1    0      0  ⎥  ⎢                        ⎥⎟
⎜⎢                   ⎥, ⎢             13         ⎥⎟
⎜⎢0  4/3  18/5  -6/5 ⎥  ⎢1/3   -1/9   ──    -1/15⎥⎟
⎜⎢                   ⎥  ⎢             15         ⎥⎟
⎜⎣1  2/3  -6/5  -18/5⎦  ⎢                        ⎥⎟
⎝                       ⎣ 0     0      0      1  ⎦⎠

In [57]:
imf.compute(smp.S(4)/-3, adr1=3, adr2=2, mode='r')
imf.M, imf.E

⎛                       ⎡1/3   -1/9   -2/15  -1/15⎤⎞
⎜⎡1   0    0      0  ⎤  ⎢                         ⎥⎟
⎜⎢                   ⎥  ⎢1/10  4/15   1/50   -7/50⎥⎟
⎜⎢0   1    0      0  ⎥  ⎢                         ⎥⎟
⎜⎢                   ⎥, ⎢              21         ⎥⎟
⎜⎢0   0   18/5  -6/5 ⎥  ⎢1/5   -7/15   ──    3/25 ⎥⎟
⎜⎢                   ⎥  ⎢              25         ⎥⎟
⎜⎣1  2/3  -6/5  -18/5⎦  ⎢                         ⎥⎟
⎝                       ⎣ 0      0      0      1  ⎦⎠

In [58]:
imf.compute(smp.S(5)/18, adr1=3, adr2=3, mode='r')
imf.M, imf.E

⎛⎡1   0    0      0  ⎤  ⎡1/3   -1/9   -2/15  -1/15⎤⎞
⎜⎢                   ⎥  ⎢                         ⎥⎟
⎜⎢0   1    0      0  ⎥  ⎢1/10  4/15   1/50   -7/50⎥⎟
⎜⎢                   ⎥, ⎢                         ⎥⎟
⎜⎢0   0    1    -1/3 ⎥  ⎢1/18  -7/54  7/30   1/30 ⎥⎟
⎜⎢                   ⎥  ⎢                         ⎥⎟
⎝⎣1  2/3  -6/5  -18/5⎦  ⎣ 0      0      0      1  ⎦⎠

In [59]:
imf.compute(smp.S(1)/3, adr1=4, adr2=3, mode='c')
imf.M, imf.E

⎛⎡1   0    0    0 ⎤  ⎡1/3   -1/9   -2/15  -1/9 ⎤⎞
⎜⎢                ⎥  ⎢                         ⎥⎟
⎜⎢0   1    0    0 ⎥  ⎢1/10  4/15   1/50   -2/15⎥⎟
⎜⎢                ⎥, ⎢                         ⎥⎟
⎜⎢0   0    1    0 ⎥  ⎢1/18  -7/54  7/30    1/9 ⎥⎟
⎜⎢                ⎥  ⎢                         ⎥⎟
⎝⎣1  2/3  -6/5  -4⎦  ⎣ 0      0      0      1  ⎦⎠

In [60]:
imf.compute(smp.S(1)/-1, adr1=4, adr2=1, mode='r')
imf.M, imf.E

⎛⎡1   0    0    0 ⎤  ⎡1/3   -1/9   -2/15  -1/9 ⎤⎞
⎜⎢                ⎥  ⎢                         ⎥⎟
⎜⎢0   1    0    0 ⎥  ⎢1/10  4/15   1/50   -2/15⎥⎟
⎜⎢                ⎥, ⎢                         ⎥⎟
⎜⎢0   0    1    0 ⎥  ⎢1/18  -7/54  7/30    1/9 ⎥⎟
⎜⎢                ⎥  ⎢                         ⎥⎟
⎝⎣0  2/3  -6/5  -4⎦  ⎣-1/3   1/9   2/15   10/9 ⎦⎠

In [61]:
imf.compute(smp.S(2)/-3, adr1=4, adr2=2, mode='r')
imf.M, imf.E

⎛⎡1  0   0    0 ⎤  ⎡1/3   -1/9   -2/15  -1/9 ⎤⎞
⎜⎢              ⎥  ⎢                         ⎥⎟
⎜⎢0  1   0    0 ⎥  ⎢1/10  4/15   1/50   -2/15⎥⎟
⎜⎢              ⎥, ⎢                         ⎥⎟
⎜⎢0  0   1    0 ⎥  ⎢1/18  -7/54  7/30    1/9 ⎥⎟
⎜⎢              ⎥  ⎢                         ⎥⎟
⎝⎣0  0  -6/5  -4⎦  ⎣-2/5  -1/15  3/25    6/5 ⎦⎠

In [62]:
imf.compute(smp.S(6)/5, adr1=4, adr2=3, mode='r')
imf.M, imf.E

⎛⎡1  0  0  0 ⎤  ⎡1/3   -1/9   -2/15  -1/9 ⎤⎞
⎜⎢           ⎥  ⎢                         ⎥⎟
⎜⎢0  1  0  0 ⎥  ⎢1/10  4/15   1/50   -2/15⎥⎟
⎜⎢           ⎥, ⎢                         ⎥⎟
⎜⎢0  0  1  0 ⎥  ⎢1/18  -7/54  7/30    1/9 ⎥⎟
⎜⎢           ⎥  ⎢                         ⎥⎟
⎝⎣0  0  0  -4⎦  ⎣-1/3  -2/9    2/5    4/3 ⎦⎠

In [63]:
imf.compute(smp.S(1)/-4, adr1=4, adr2=4, mode='r')
imf.M, imf.E

⎛⎡1  0  0  0⎤  ⎡1/3   -1/9   -2/15  -1/9 ⎤⎞
⎜⎢          ⎥  ⎢                         ⎥⎟
⎜⎢0  1  0  0⎥  ⎢1/10  4/15   1/50   -2/15⎥⎟
⎜⎢          ⎥, ⎢                         ⎥⎟
⎜⎢0  0  1  0⎥  ⎢1/18  -7/54  7/30    1/9 ⎥⎟
⎜⎢          ⎥  ⎢                         ⎥⎟
⎝⎣0  0  0  1⎦  ⎣1/12  1/18   -1/10  -1/3 ⎦⎠

# Конец расчета 1

# Начало расчета 2

In [77]:
Cm_new2 = smp.Matrix(IC)
for x in range(rows):
    for y in range(cols):
        elem = smp.S(int(Cm[x,y]))
        Cm_new2[x,y] = elem
Cm_new2

⎡3   1  1   1 ⎤
⎢             ⎥
⎢-1  3  -1  1 ⎥
⎢             ⎥
⎢-1  1  3   -1⎥
⎢             ⎥
⎣1   1  -1  -3⎦

In [78]:
imf2 = InvMatrixFinder(Cm_new2)
imf2.M, imf2.E

⎛⎡3   1  1   1 ⎤  ⎡1  0  0  0⎤⎞
⎜⎢             ⎥  ⎢          ⎥⎟
⎜⎢-1  3  -1  1 ⎥  ⎢0  1  0  0⎥⎟
⎜⎢             ⎥, ⎢          ⎥⎟
⎜⎢-1  1  3   -1⎥  ⎢0  0  1  0⎥⎟
⎜⎢             ⎥  ⎢          ⎥⎟
⎝⎣1   1  -1  -3⎦  ⎣0  0  0  1⎦⎠

In [79]:
imf2.compute(smp.S(2)/1, adr1=1, adr2=2, mode='r')
imf2.M, imf2.E

⎛⎡1   7  -1  3 ⎤  ⎡1  2  0  0⎤⎞
⎜⎢             ⎥  ⎢          ⎥⎟
⎜⎢-1  3  -1  1 ⎥  ⎢0  1  0  0⎥⎟
⎜⎢             ⎥, ⎢          ⎥⎟
⎜⎢-1  1  3   -1⎥  ⎢0  0  1  0⎥⎟
⎜⎢             ⎥  ⎢          ⎥⎟
⎝⎣1   1  -1  -3⎦  ⎣0  0  0  1⎦⎠

In [80]:
imf2.compute(smp.S(7)/-1, adr1=2, adr2=1, mode='c')
imf2.M, imf2.E

⎛⎡1   0   -1  3 ⎤  ⎡1  -5  0  0⎤⎞
⎜⎢              ⎥  ⎢           ⎥⎟
⎜⎢-1  10  -1  1 ⎥  ⎢0  1   0  0⎥⎟
⎜⎢              ⎥, ⎢           ⎥⎟
⎜⎢-1  8   3   -1⎥  ⎢0  0   1  0⎥⎟
⎜⎢              ⎥  ⎢           ⎥⎟
⎝⎣1   -6  -1  -3⎦  ⎣0  0   0  1⎦⎠

In [81]:
imf2.compute(smp.S(1)/1, adr1=3, adr2=1, mode='c')
imf2.M, imf2.E

⎛⎡1   0   0   3 ⎤  ⎡1  -5  1  0⎤⎞
⎜⎢              ⎥  ⎢           ⎥⎟
⎜⎢-1  10  -2  1 ⎥  ⎢0  1   0  0⎥⎟
⎜⎢              ⎥, ⎢           ⎥⎟
⎜⎢-1  8   2   -1⎥  ⎢0  0   1  0⎥⎟
⎜⎢              ⎥  ⎢           ⎥⎟
⎝⎣1   -6  0   -3⎦  ⎣0  0   0  1⎦⎠

In [82]:
imf2.compute(smp.S(3)/-1, adr1=4, adr2=1, mode='c')
imf2.M, imf2.E

⎛⎡1   0   0   0 ⎤  ⎡1  -5  1  -3⎤⎞
⎜⎢              ⎥  ⎢            ⎥⎟
⎜⎢-1  10  -2  4 ⎥  ⎢0  1   0  0 ⎥⎟
⎜⎢              ⎥, ⎢            ⎥⎟
⎜⎢-1  8   2   2 ⎥  ⎢0  0   1  0 ⎥⎟
⎜⎢              ⎥  ⎢            ⎥⎟
⎝⎣1   -6  0   -6⎦  ⎣0  0   0  1 ⎦⎠

In [83]:
imf2.compute(smp.S(1)/-1, adr1=2, adr2=4, mode='c')
imf2.M, imf2.E

⎛⎡1   0  0   0 ⎤  ⎡1  -2  1  -3⎤⎞
⎜⎢             ⎥  ⎢            ⎥⎟
⎜⎢-1  6  -2  4 ⎥  ⎢0  1   0  0 ⎥⎟
⎜⎢             ⎥, ⎢            ⎥⎟
⎜⎢-1  6  2   2 ⎥  ⎢0  0   1  0 ⎥⎟
⎜⎢             ⎥  ⎢            ⎥⎟
⎝⎣1   0  0   -6⎦  ⎣0  -1  0  1 ⎦⎠

In [84]:
imf2.compute(smp.S(1)/-1, adr1=2, adr2=4, mode='c')
imf2.M, imf2.E

⎛⎡1   0  0   0 ⎤  ⎡1  1   1  -3⎤⎞
⎜⎢             ⎥  ⎢            ⎥⎟
⎜⎢-1  2  -2  4 ⎥  ⎢0  1   0  0 ⎥⎟
⎜⎢             ⎥, ⎢            ⎥⎟
⎜⎢-1  4  2   2 ⎥  ⎢0  0   1  0 ⎥⎟
⎜⎢             ⎥  ⎢            ⎥⎟
⎝⎣1   6  0   -6⎦  ⎣0  -2  0  1 ⎦⎠

In [85]:
imf2.compute(smp.S(1)/1, adr1=2, adr2=1, mode='r')
imf2.M, imf2.E

⎛⎡1   0  0   0 ⎤  ⎡1  1   1  -3⎤⎞
⎜⎢             ⎥  ⎢            ⎥⎟
⎜⎢0   2  -2  4 ⎥  ⎢1  2   1  -3⎥⎟
⎜⎢             ⎥, ⎢            ⎥⎟
⎜⎢-1  4  2   2 ⎥  ⎢0  0   1  0 ⎥⎟
⎜⎢             ⎥  ⎢            ⎥⎟
⎝⎣1   6  0   -6⎦  ⎣0  -2  0  1 ⎦⎠

In [86]:
imf2.compute(smp.S(1)/2, adr1=2, adr2=3, mode='c')
imf2.M, imf2.E

⎛⎡1   0  0   0 ⎤  ⎡1  3/2  1  -3⎤⎞
⎜⎢             ⎥  ⎢             ⎥⎟
⎜⎢0   1  -2  4 ⎥  ⎢1  5/2  1  -3⎥⎟
⎜⎢             ⎥, ⎢             ⎥⎟
⎜⎢-1  5  2   2 ⎥  ⎢0  1/2  1  0 ⎥⎟
⎜⎢             ⎥  ⎢             ⎥⎟
⎝⎣1   6  0   -6⎦  ⎣0  -2   0  1 ⎦⎠

In [87]:
imf2.compute(smp.S(2)/1, adr1=3, adr2=2, mode='c')
imf2.M, imf2.E

⎛⎡1   0  0   0 ⎤  ⎡1  3/2  4   -3⎤⎞
⎜⎢             ⎥  ⎢              ⎥⎟
⎜⎢0   1  0   4 ⎥  ⎢1  5/2  6   -3⎥⎟
⎜⎢             ⎥, ⎢              ⎥⎟
⎜⎢-1  5  12  2 ⎥  ⎢0  1/2  2   0 ⎥⎟
⎜⎢             ⎥  ⎢              ⎥⎟
⎝⎣1   6  12  -6⎦  ⎣0  -2   -4  1 ⎦⎠

In [88]:
imf2.compute(smp.S(4)/-1, adr1=4, adr2=2, mode='c')
imf2.M, imf2.E

⎛⎡1   0  0    0 ⎤  ⎡1  3/2  4   -9 ⎤⎞
⎜⎢              ⎥  ⎢               ⎥⎟
⎜⎢0   1  0    0 ⎥  ⎢1  5/2  6   -13⎥⎟
⎜⎢              ⎥, ⎢               ⎥⎟
⎜⎢-1  5  12  -18⎥  ⎢0  1/2  2   -2 ⎥⎟
⎜⎢              ⎥  ⎢               ⎥⎟
⎝⎣1   6  12  -30⎦  ⎣0  -2   -4   9 ⎦⎠

In [89]:
imf2.compute(smp.S(1)/1, adr1=3, adr2=1, mode='r')
imf2.M, imf2.E

⎛⎡1  0  0    0 ⎤  ⎡1  3/2  4   -9 ⎤⎞
⎜⎢             ⎥  ⎢               ⎥⎟
⎜⎢0  1  0    0 ⎥  ⎢1  5/2  6   -13⎥⎟
⎜⎢             ⎥, ⎢               ⎥⎟
⎜⎢0  5  12  -18⎥  ⎢1   2   6   -11⎥⎟
⎜⎢             ⎥  ⎢               ⎥⎟
⎝⎣1  6  12  -30⎦  ⎣0  -2   -4   9 ⎦⎠

In [90]:
imf2.compute(smp.S(5)/-1, adr1=3, adr2=2, mode='r')
imf2.M, imf2.E

⎛⎡1  0  0    0 ⎤  ⎡1    3/2    4   -9 ⎤⎞
⎜⎢             ⎥  ⎢                   ⎥⎟
⎜⎢0  1  0    0 ⎥  ⎢1    5/2    6   -13⎥⎟
⎜⎢             ⎥, ⎢                   ⎥⎟
⎜⎢0  0  12  -18⎥  ⎢-4  -21/2  -24  54 ⎥⎟
⎜⎢             ⎥  ⎢                   ⎥⎟
⎝⎣1  6  12  -30⎦  ⎣0    -2    -4    9 ⎦⎠

In [91]:
imf2.compute(smp.S(1)/12, adr1=3, adr2=3, mode='r')
imf2.M, imf2.E

⎛⎡1  0  0    0  ⎤  ⎡ 1    3/2   4   -9 ⎤⎞
⎜⎢              ⎥  ⎢                   ⎥⎟
⎜⎢0  1  0    0  ⎥  ⎢ 1    5/2   6   -13⎥⎟
⎜⎢              ⎥, ⎢                   ⎥⎟
⎜⎢0  0  1   -3/2⎥  ⎢-1/3  -7/8  -2  9/2⎥⎟
⎜⎢              ⎥  ⎢                   ⎥⎟
⎝⎣1  6  12  -30 ⎦  ⎣ 0     -2   -4   9 ⎦⎠

In [92]:
imf2.compute(smp.S(3)/2, adr1=4, adr2=3, mode='c')
imf2.M, imf2.E

⎛⎡1  0  0    0 ⎤  ⎡ 1    3/2   4   -3 ⎤⎞
⎜⎢             ⎥  ⎢                   ⎥⎟
⎜⎢0  1  0    0 ⎥  ⎢ 1    5/2   6   -4 ⎥⎟
⎜⎢             ⎥, ⎢                   ⎥⎟
⎜⎢0  0  1    0 ⎥  ⎢-1/3  -7/8  -2  3/2⎥⎟
⎜⎢             ⎥  ⎢                   ⎥⎟
⎝⎣1  6  12  -12⎦  ⎣ 0     -2   -4   3 ⎦⎠

In [93]:
imf2.compute(smp.S(1)/-1, adr1=4, adr2=1, mode='r')
imf2.M, imf2.E

⎛⎡1  0  0    0 ⎤  ⎡ 1    3/2   4   -3 ⎤⎞
⎜⎢             ⎥  ⎢                   ⎥⎟
⎜⎢0  1  0    0 ⎥  ⎢ 1    5/2   6   -4 ⎥⎟
⎜⎢             ⎥, ⎢                   ⎥⎟
⎜⎢0  0  1    0 ⎥  ⎢-1/3  -7/8  -2  3/2⎥⎟
⎜⎢             ⎥  ⎢                   ⎥⎟
⎝⎣0  6  12  -12⎦  ⎣ -1   -7/2  -8   6 ⎦⎠

In [94]:
imf2.compute(smp.S(1)/2, adr1=2, adr2=4, mode='c')
imf2.M, imf2.E

⎛⎡1  0  0    0 ⎤  ⎡ 1     0    4   -3 ⎤⎞
⎜⎢             ⎥  ⎢                   ⎥⎟
⎜⎢0  1  0    0 ⎥  ⎢ 1    1/2   6   -4 ⎥⎟
⎜⎢             ⎥, ⎢                   ⎥⎟
⎜⎢0  0  1    0 ⎥  ⎢-1/3  -1/8  -2  3/2⎥⎟
⎜⎢             ⎥  ⎢                   ⎥⎟
⎝⎣0  0  12  -12⎦  ⎣ -1   -1/2  -8   6 ⎦⎠

In [95]:
imf2.compute(smp.S(1)/1, adr1=3, adr2=4, mode='c')
imf2.M, imf2.E

⎛⎡1  0  0   0 ⎤  ⎡ 1     0     1    -3 ⎤⎞
⎜⎢            ⎥  ⎢                     ⎥⎟
⎜⎢0  1  0   0 ⎥  ⎢ 1    1/2    2    -4 ⎥⎟
⎜⎢            ⎥, ⎢                     ⎥⎟
⎜⎢0  0  1   0 ⎥  ⎢-1/3  -1/8  -1/2  3/2⎥⎟
⎜⎢            ⎥  ⎢                     ⎥⎟
⎝⎣0  0  0  -12⎦  ⎣ -1   -1/2   -2    6 ⎦⎠

In [96]:
imf2.compute(smp.S(1)/-12, adr1=4, adr2=4, mode='r')
imf2.M, imf2.E

⎛⎡1  0  0  0⎤  ⎡ 1     0     1     -3 ⎤⎞
⎜⎢          ⎥  ⎢                      ⎥⎟
⎜⎢0  1  0  0⎥  ⎢ 1    1/2    2     -4 ⎥⎟
⎜⎢          ⎥, ⎢                      ⎥⎟
⎜⎢0  0  1  0⎥  ⎢-1/3  -1/8  -1/2  3/2 ⎥⎟
⎜⎢          ⎥  ⎢                      ⎥⎟
⎝⎣0  0  0  1⎦  ⎣1/12  1/24  1/6   -1/2⎦⎠

# Конец расчета 2

In [75]:
Cm, imf.E, imf.M

⎛⎡3   1  1   1 ⎤  ⎡1/3   -1/9   -2/15  -1/9 ⎤  ⎡1  0  0  0⎤⎞
⎜⎢             ⎥  ⎢                         ⎥  ⎢          ⎥⎟
⎜⎢-1  3  -1  1 ⎥  ⎢1/10  4/15   1/50   -2/15⎥  ⎢0  1  0  0⎥⎟
⎜⎢             ⎥, ⎢                         ⎥, ⎢          ⎥⎟
⎜⎢-1  1  3   -1⎥  ⎢1/18  -7/54  7/30    1/9 ⎥  ⎢0  0  1  0⎥⎟
⎜⎢             ⎥  ⎢                         ⎥  ⎢          ⎥⎟
⎝⎣1   1  -1  -3⎦  ⎣1/12  1/18   -1/10  -1/3 ⎦  ⎣0  0  0  1⎦⎠

In [67]:
imf.E*Cm

⎡  17    -11          31  ⎤
⎢  ──    ────  7/45   ──  ⎥
⎢  15     45          45  ⎥
⎢                         ⎥
⎢         59          56  ⎥
⎢-3/25    ──   2/75   ──  ⎥
⎢         75          75  ⎥
⎢                         ⎥
⎢  47          209   -173 ⎥
⎢ ───    1/90  ───   ─────⎥
⎢ 270          270    270 ⎥
⎢                         ⎥
⎢        -11    11    223 ⎥
⎢-7/180  ────  ───    ─── ⎥
⎣         60   180    180 ⎦

In [56]:
Cm2

⎡1/4   -1/12  -1/12  1/12 ⎤
⎢                         ⎥
⎢1/12   1/4   1/12   1/12 ⎥
⎢                         ⎥
⎢1/12  -1/12   1/4   -1/12⎥
⎢                         ⎥
⎣1/12  1/12   -1/12  -1/4 ⎦

In [66]:
Cm[2,:]*smp.S(3)

[-3  3  9  -3]

In [67]:
E = np.eye(4)
E
print(C[:,2]*2)
print(C[2,:]*2)
print(C, E, sep='\n')

[[ 2.]
 [-2.]
 [ 6.]
 [-2.]]
[[-2.  2.  6. -2.]]
[[ 3.  1.  1.  1.]
 [-1.  3. -1.  1.]
 [-1.  1.  3. -1.]
 [ 1.  1. -1. -3.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [74]:
C2 = np.copy(C)
C2[:,2] = C2[:,2]*2
print(C2)
print(C.shape)

[[ 3.  1.  2.  1.]
 [-1.  3. -2.  1.]
 [-1.  1.  6. -1.]
 [ 1.  1. -2. -3.]]
(4, 4)


In [17]:
type(smp.S(1))

sympy.core.numbers.One